server:
  port: 8080




spring:
  # 以下为数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1/udmc?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    # url: jdbc:oracle:thin:@127.0.0.1:1521:demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      initial-size: 20 # 连接池初始化大小
      min-idle: 5      # 连接池最小连接数
      max-active: 2500  # 连接池最大连接数
      max-wait: 60000   # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 'x'
      test-while-idle: true # 检测连接是否有效
      test-on-borrow: true  # 申请连接时执行validationQuery检测连接是否有效。做了这个配置会降低性能。
      test-on-return: true  # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      pool-prepared-statements: true # 是否缓存preparedStatement，也就是PSCache。打开PSCache
      max-pool-prepared-statement-per-connection-size: 20 # 指定每个连接上PSCache的大小。要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
        log4j:
          enabled: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # 监控页面配置
      stat-view-servlet:
        enabled: true
        login-username: ${spring.datasource.username}
        login-password: ${spring.datasource.password}
        allow: 127.0.0.1
        deny:
        url-pattern: /druid/*
      web-stat-filter:
        exclusions: \*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*

# 以下为dubbo provider相关配置
dubbo:
  application:
    name: dbagent # dubbo提供者的别名，只是个标识
  registry:
    # address: zookeeper://127.0.0.1:2181
    address: N/A
  #注册中心类型
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.thinkdifferent.dbagent.service